version: "3.9"

services:
  backend:
    image: popsicles/anime-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anime-backend
    ports:
      - "8000:8000"

  frontend:
    image: popsicles/anime-frontend:latest
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    container_name: anime-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
